project:
  type: website
  output-dir: docs

website:
  title: "Sammi Rosser"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Talks and Posters"
        menu:
        - href: talks/2511_nhsrpycom/2511_nhsrpycom.qmd
          text: RPySOC 2025 Keynote
        - href: talks/sw25_vidigi/sw25.qmd
          text: OR Society Simulation Workshop 2025 Poster
        - href: talks/2411_nhsr/2411_nhsr.qmd
          text: RPySOC 2024 Lightning Talk
        - href: talks/2402_dsnhs/2402_dsnhs.qmd
          text: SWAIH Insight Talk
        - href: talks/2310_nhsr/2310_nhsr.qmd
          text: RPySOC 2023 Plenary Talk
      - text: "Projects"
        menu:
        - href: projects/des_playground.qmd
          text: The DES Playground

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    include-in-header:
      - text: |
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
